title: TouFu
permalink: /:year/:year-:month-:day/:title.html

exclude: [ ".gitignore", "README.md", "CNAME" ]

highlighter: rouge

sass:
    style: :compressed

url: "http://tourfoodstuff.com"

disqus_short_name: 'tourfoodstuff'

google_tracking_id: 'UA-25258167-6'
